// ── hadrians ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
// ── Hadrian's Wall ────────────────────────────────────────────
  {
    id: 'hadrians', name: "Hadrian's Wall", icon: '🧱', genre: 'Roll & Write · Solo Campaign',
    color: '#6a4a2a', bgColor: '#fff8f0', dimColor: '#c09060',
    personalBestField: 'score',
    logFields: [
      { id: 'win',        label: 'Win?',          type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'difficulty', label: 'Difficulty',    type: 'select', options: ['Easy','Medium','Hard'] },
      { id: 'fort',       label: 'Fort',          type: 'select', options: ['Any', 'Fort 1: Segedunum', 'Fort 2: Pons Aelius', 'Fort 3: Condercum', 'Fort 4: Vindobala', 'Fort 5: Onnum', 'Fort 6: Cilurnum', 'Fort 7: Brocolitia', 'Fort 8: Vercovicium', 'Fort 9: Aesica', 'Fort 10: Magnis', 'Fort 11: Banna', 'Fort 12: Camboglanna', 'Fort 13: Uxelodunum', 'Fort 14: Aballava', 'Fort 15: Coggabata', 'Fort 16: Maia'] },
      { id: 'score',      label: 'Final Score',   type: 'number', min: -50, max: 120, default: 60 },
      { id: 'renown',     label: 'Renown',        type: 'number', min: 0, max: 40, default: 0 },
      { id: 'piety',      label: 'Piety',         type: 'number', min: 0, max: 20, default: 0 },
      { id: 'valour',     label: 'Valour',        type: 'number', min: 0, max: 30, default: 0 },
      { id: 'discipline', label: 'Discipline',    type: 'number', min: 0, max: 30, default: 0 },
      { id: 'pathcards',  label: 'Path Cards',    type: 'number', min: 0, max: 20, default: 0 },
      { id: 'disdain',    label: 'Disdain (−)',   type: 'number', min: 0, max: 30, default: 0 },
    ],
    personalBestContext: 'difficulty',
    personalBestTitle: 'Best Score by Difficulty',

    customStatsTitle: 'Difficulty Breakdown',
    customStats: [
      { label: 'Easy',   type: 'ratio', field: 'difficulty', value: 'Easy' },
      { label: 'Medium', type: 'ratio', field: 'difficulty', value: 'Medium' },
      { label: 'Hard',   type: 'ratio', field: 'difficulty', value: 'Hard' },
    ],

    customStats2Title: 'Score Components (Best Win)',
    customStats2: [
      { label: 'Renown',     type: 'best_win', field: 'renown' },
      { label: 'Piety',      type: 'best_win', field: 'piety' },
      { label: 'Valour',     type: 'best_win', field: 'valour' },
      { label: 'Discipline', type: 'best_win', field: 'discipline' },
      { label: 'Path Cards', type: 'best_win', field: 'pathcards' },
    ],

    achievements: [
      { id: 'hw_first',   icon: '🌟', tier: 'bronze', pts: 10, name: 'First Watch',
        desc: 'Win your first game',
        check: { type: 'min_wins', count: 1 } },
      { id: 'hw_score70', icon: '🏅', tier: 'bronze', pts: 10, name: 'Solid Defense',
        desc: 'Score 70+ points',
        check: { type: 'field_gte', field: 'score', value: 70 } },
      { id: 'hw_score80', icon: '🛡️', tier: 'silver', pts: 20, name: 'Fortified',
        desc: 'Score 80+ points',
        check: { type: 'field_gte', field: 'score', value: 80 } },
      { id: 'hw_score90', icon: '⚔️',  tier: 'gold',   pts: 35, name: 'Impenetrable',
        desc: 'Score 90+ points',
        check: { type: 'field_gte', field: 'score', value: 90 } },
      { id: 'hw_hard',    icon: '🪖', tier: 'gold',   pts: 40, name: 'Hard Campaign',
        desc: 'Win on Hard difficulty',
        check: { type: 'win_with_field', field: 'difficulty', value: 'Hard' } },
      { id: 'hw_10plays', icon: '🎮', tier: 'silver', pts: 20, name: 'Centurion',
        desc: 'Play 10 games',
        check: { type: 'min_plays', count: 10 } },
      // ── Fort campaign achievements ──
      { id: 'hw_f1', icon: '🧱', tier: 'bronze', pts: 10, name: 'Segedunum Cleared',
        desc: 'Win Fort 1: Segedunum',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 1: Segedunum' } },
      { id: 'hw_f2', icon: '🧱', tier: 'bronze', pts: 10, name: 'Pons Aelius Cleared',
        desc: 'Win Fort 2: Pons Aelius',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 2: Pons Aelius' } },
      { id: 'hw_f3', icon: '🧱', tier: 'bronze', pts: 10, name: 'Condercum Cleared',
        desc: 'Win Fort 3: Condercum',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 3: Condercum' } },
      { id: 'hw_f4', icon: '🧱', tier: 'bronze', pts: 10, name: 'Vindobala Cleared',
        desc: 'Win Fort 4: Vindobala',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 4: Vindobala' } },
      { id: 'hw_f5', icon: '🧱', tier: 'bronze', pts: 10, name: 'Onnum Cleared',
        desc: 'Win Fort 5: Onnum',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 5: Onnum' } },
      { id: 'hw_f6', icon: '🧱', tier: 'bronze', pts: 10, name: 'Cilurnum Cleared',
        desc: 'Win Fort 6: Cilurnum',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 6: Cilurnum' } },
      { id: 'hw_f7', icon: '🧱', tier: 'bronze', pts: 10, name: 'Brocolitia Cleared',
        desc: 'Win Fort 7: Brocolitia',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 7: Brocolitia' } },
      { id: 'hw_f8', icon: '🧱', tier: 'bronze', pts: 10, name: 'Vercovicium Cleared',
        desc: 'Win Fort 8: Vercovicium',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 8: Vercovicium' } },
      { id: 'hw_f9', icon: '🧱', tier: 'silver', pts: 15, name: 'Aesica Cleared',
        desc: 'Win Fort 9: Aesica',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 9: Aesica' } },
      { id: 'hw_f10', icon: '🧱', tier: 'silver', pts: 15, name: 'Magnis Cleared',
        desc: 'Win Fort 10: Magnis',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 10: Magnis' } },
      { id: 'hw_f11', icon: '🧱', tier: 'silver', pts: 15, name: 'Banna Cleared',
        desc: 'Win Fort 11: Banna',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 11: Banna' } },
      { id: 'hw_f12', icon: '🧱', tier: 'silver', pts: 15, name: 'Camboglanna Cleared',
        desc: 'Win Fort 12: Camboglanna',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 12: Camboglanna' } },
      { id: 'hw_f13', icon: '🧱', tier: 'silver', pts: 15, name: 'Uxelodunum Cleared',
        desc: 'Win Fort 13: Uxelodunum',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 13: Uxelodunum' } },
      { id: 'hw_f14', icon: '🧱', tier: 'silver', pts: 15, name: 'Aballava Cleared',
        desc: 'Win Fort 14: Aballava',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 14: Aballava' } },
      { id: 'hw_f15', icon: '🧱', tier: 'silver', pts: 15, name: 'Coggabata Cleared',
        desc: 'Win Fort 15: Coggabata',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 15: Coggabata' } },
      { id: 'hw_f16', icon: '🧱', tier: 'silver', pts: 15, name: 'Maia Cleared',
        desc: 'Win Fort 16: Maia',
        check: { type: 'win_with_field', field: 'fort', value: 'Fort 16: Maia' } },
      { id: 'hw_campaign', icon: '🗺️', tier: 'gold', pts: 100, name: 'Wall Builder',
        desc: 'Win all 16 forts and complete the solo campaign',
        check: { type: 'all_achievements', ids: ['hw_f1', 'hw_f2', 'hw_f3', 'hw_f4', 'hw_f5', 'hw_f6', 'hw_f7', 'hw_f8', 'hw_f9', 'hw_f10', 'hw_f11', 'hw_f12', 'hw_f13', 'hw_f14', 'hw_f15', 'hw_f16'] } },

      // ── Category achievements ──
      { id: 'hw_renown20',    icon: '⭐', tier: 'silver', pts: 20, name: 'Renowned',
        desc: 'Score 20+ Renown in a game',
        check: { type: 'field_gte', field: 'renown', value: 20 } },
      { id: 'hw_nodisdain',   icon: '✅', tier: 'gold',   pts: 40, name: 'Flawless Garrison',
        desc: 'Win with 0 Disdain',
        check: { type: 'win_field_eq', field: 'disdain', value: 0 } },
      { id: 'hw_discipline20',icon: '🪖', tier: 'silver', pts: 20, name: 'Iron Discipline',
        desc: 'Score 20+ Discipline in a game',
        check: { type: 'field_gte', field: 'discipline', value: 20 } },

      { id: 'hw_plat',    icon: '💎', tier: 'plat',   pts: 100, name: "Hadrian's Champion",
        desc: "Unlock all other Hadrian's Wall achievements",
        check: { type: 'all_achievements', ids: ['hw_first','hw_score70','hw_score80','hw_score90','hw_hard','hw_10plays','hw_renown20','hw_nodisdain','hw_discipline20','hw_campaign','hw_f1','hw_f2','hw_f3','hw_f4','hw_f5','hw_f6','hw_f7','hw_f8','hw_f9','hw_f10','hw_f11','hw_f12','hw_f13','hw_f14','hw_f15','hw_f16'] } },
    ]
  }
);
