// ── Meta Achievements ──
window.META_DEFINITIONS = [
  // ── Active achievements ────────────────────────────────────
  { id: 'm_first_win',    icon: '🌟', tier: 'bronze', pts: 10,  category: 'active',
    name: 'First Blood',        desc: 'Win your first game of any kind',
    check: { type: 'total_wins_gte', count: 1 } },
  { id: 'm_5diff',        icon: '🎲', tier: 'silver', pts: 30,  category: 'active',
    name: 'Variety Pack',       desc: 'Play 5 different games',
    check: { type: 'games_played_gte', count: 5 } },
  { id: 'm_10diff',       icon: '📚', tier: 'gold',   pts: 40,  category: 'active',
    name: 'Eclectic Gamer',     desc: 'Play 10 different games',
    check: { type: 'games_played_gte', count: 10 } },
  { id: 'm_20diff',       icon: '🗂️', tier: 'gold',   pts: 60,  category: 'active',
    name: 'Deep Library',       desc: 'Play 20 different games',
    check: { type: 'games_played_gte', count: 20 } },
  { id: 'm_streak3',      icon: '🔥', tier: 'silver', pts: 25,  category: 'active',
    name: 'Hot Streak',         desc: 'Win 3 games in a row across any games',
    check: { type: 'win_streak', count: 3 } },
  { id: 'm_streak5',      icon: '🔥', tier: 'gold',   pts: 50,  category: 'active',
    name: 'On Fire',            desc: 'Win 5 games in a row across any games',
    check: { type: 'win_streak', count: 5 } },
  { id: 'm_streak10',     icon: '🌋', tier: 'gold',   pts: 80,  category: 'active',
    name: 'Unstoppable',        desc: 'Win 10 games in a row across any games',
    check: { type: 'win_streak', count: 10 } },
  { id: 'm_week',         icon: '🌈', tier: 'silver', pts: 35,  category: 'active',
    name: 'Game Week',          desc: 'Play 5 different games within any 7-day period',
    check: { type: 'n_different_games_in_week', count: 5 } },
  { id: 'm_week7',        icon: '🎯', tier: 'gold',   pts: 60,  category: 'active',
    name: 'Mega Week',          desc: 'Play 7 different games within any 7-day period',
    check: { type: 'n_different_games_in_week', count: 7 } },
  { id: 'm_scifi',        icon: '🛸', tier: 'gold',   pts: 40,  category: 'active',
    name: 'Sci-Fi Weekend',     desc: "Win Warp's Edge and Under Falling Skies on the same day",
    check: { type: 'cross_same_day', games: ['warps','skies'] } },
  { id: 'm_deduction',    icon: '🔍', tier: 'gold',   pts: 40,  category: 'active',
    name: 'Master Deductionist', desc: 'Win Turing Machine and Search for Planet X on the same day',
    check: { type: 'cross_same_day', games: ['turing','planetx'] } },
  { id: 'm_island_day',   icon: '🏝️', tier: 'gold',   pts: 40,  category: 'active',
    name: 'Island Day',         desc: 'Win Spirit Island and Friday on the same day',
    check: { type: 'cross_same_day', games: ['spiritisland','friday'] } },
  { id: 'm_rail_day',     icon: '🚇', tier: 'gold',   pts: 40,  category: 'active',
    name: 'Rail Planner',       desc: 'Win two Next Station games on the same day',
    check: { type: 'cross_same_day', games: ['nextstationlondon','nextstationparis'] } },
  { id: 'm_solo_sunday',  icon: '☀️',  tier: 'gold',   pts: 50,  category: 'active',
    name: 'Solo Sunday',        desc: 'Win 5 different games in a single day',
    check: { type: 'n_different_games_won_same_day', count: 5 } },
  { id: 'm_100pts',       icon: '💯', tier: 'bronze', pts: 10,  category: 'active',
    name: 'Century Club',       desc: 'Earn 100 total achievement points',
    check: { type: 'total_pts_gte', count: 100 } },
  { id: 'm_500pts',       icon: '⭐', tier: 'silver', pts: 25,  category: 'active',
    name: 'Elite Collector',    desc: 'Earn 500 total achievement points',
    check: { type: 'total_pts_gte', count: 500 } },
  { id: 'm_1000pts',      icon: '🏅', tier: 'gold',   pts: 50,  category: 'active',
    name: 'Grand Master',       desc: 'Earn 1000 total achievement points',
    check: { type: 'total_pts_gte', count: 1000 } },
  { id: 'm_2500pts',      icon: '💫', tier: 'gold',   pts: 75,  category: 'active',
    name: 'Achievement Hunter', desc: 'Earn 2500 total achievement points',
    check: { type: 'total_pts_gte', count: 2500 } },
  { id: 'm_5000pts',      icon: '👑', tier: 'gold',   pts: 100, category: 'active',
    name: 'Legend',             desc: 'Earn 5000 total achievement points',
    check: { type: 'total_pts_gte', count: 5000 } },
  { id: 'm_10000pts',     icon: '🏛️', tier: 'plat',   pts: 150, category: 'active',
    name: 'Immortal',           desc: 'Earn 10000 total achievement points',
    check: { type: 'total_pts_gte', count: 10000 } },
  { id: 'm_25plays',      icon: '📅', tier: 'bronze', pts: 10,  category: 'active',
    name: 'Dedicated',          desc: 'Log 25 total plays',
    check: { type: 'total_plays_gte', count: 25 } },
  { id: 'm_100plays',     icon: '📅', tier: 'silver', pts: 25,  category: 'active',
    name: 'Veteran',            desc: 'Log 100 total plays',
    check: { type: 'total_plays_gte', count: 100 } },
  { id: 'm_250plays',     icon: '📅', tier: 'gold',   pts: 50,  category: 'active',
    name: 'Marathon Gamer',     desc: 'Log 250 total plays',
    check: { type: 'total_plays_gte', count: 250 } },
  { id: 'm_500plays',     icon: '📅', tier: 'gold',   pts: 75,  category: 'active',
    name: 'Obsessed',           desc: 'Log 500 total plays',
    check: { type: 'total_plays_gte', count: 500 } },
  { id: 'm_solo_all',     icon: '🧘', tier: 'silver', pts: 30,  category: 'active',
    name: 'Committed Solo Player', desc: 'Earn platinum in 3 different games',
    check: { type: 'plat_count_gte', count: 3 } },
  { id: 'm_dungeon_adv',  icon: '⚔️',  tier: 'gold',   pts: 45,  category: 'active',
    name: 'Dungeon Adventurer',  desc: 'Win Spirit Island, One Deck Dungeon, and Frosthaven',
    check: { type: 'all_games_won_subset', games: ['spiritisland','onedeck','frosthaven'] } },
  { id: 'm_puzzle_master',icon: '🧩', tier: 'gold',   pts: 45,  category: 'active',
    name: 'Puzzle Master',      desc: 'Win Turing Machine, Search for Planet X, and Cascadia',
    check: { type: 'all_games_won_subset', games: ['turing','planetx','cascadia'] } },
  { id: 'm_tiny_games',   icon: '🃏', tier: 'silver', pts: 30,  category: 'active',
    name: 'Micro Gamer',        desc: 'Win Sprawlopolis, Orchard, and Palm Island',
    check: { type: 'all_games_won_subset', games: ['sprawlopolis','orchard','palm'] } },
  { id: 'm_campaign',     icon: '📖', tier: 'gold',   pts: 50,  category: 'active',
    name: 'Campaigner',         desc: 'Complete a full Jaws of the Lion campaign',
    check: { type: 'campaign_complete', gameId: 'jawsoflion' } },
  { id: 'm_roll_write',   icon: '✏️',  tier: 'silver', pts: 35,  category: 'active',
    name: 'Roll & Write Master', desc: 'Win all three Next Station games',
    check: { type: 'all_games_won_subset', games: ['nextstationlondon','nextstationparis','nextstationtokyo'] } },
  { id: 'm_network',      icon: '🗺️', tier: 'gold',   pts: 45,  category: 'active',
    name: 'Network Builder',    desc: 'Win Next Station London, Paris, and Tokyo on the same day',
    check: { type: 'cross_same_day', games: ['nextstationlondon','nextstationparis','nextstationtokyo'] } },

  // ── Completionist achievements ─────────────────────────────
  { id: 'mc_all_played',  icon: '📚', tier: 'silver', pts: 50,  category: 'completionist',
    name: 'Full Library',       desc: 'Log at least one play of every game in your library',
    check: { type: 'all_games_played' } },
  { id: 'mc_all_won',     icon: '🏆', tier: 'gold',   pts: 100, category: 'completionist',
    name: 'Undefeated',         desc: 'Win at least once in every game in your library',
    check: { type: 'all_games_won' } },
  { id: 'mc_5plat',       icon: '💎', tier: 'gold',   pts: 100, category: 'completionist',
    name: 'Platinum Collector', desc: 'Earn platinum in 5 games',
    check: { type: 'plat_count_gte', count: 5 } },
  { id: 'mc_10plat',      icon: '💠', tier: 'gold',   pts: 150, category: 'completionist',
    name: 'Platinum Hoarder',   desc: 'Earn platinum in 10 games',
    check: { type: 'plat_count_gte', count: 10 } },
  { id: 'mc_all_plat',    icon: '🌟', tier: 'plat',   pts: 200, category: 'completionist',
    name: 'Platinum Master',    desc: 'Earn the platinum trophy in every game',
    check: { type: 'all_plat_achievements' } },

  // ── Seasonal achievements ──────────────────────────────────
  { id: 'm_cal_month',   icon: '📅', tier: 'silver', pts: 40,  category: 'seasonal',
    name: 'Perfect Month',      desc: 'Play a game on every single day of a calendar month in the same year',
    check: { type: 'played_every_day_of_month' } },
  { id: 'm_cal_year',    icon: '🗓️', tier: 'gold',   pts: 150, category: 'seasonal',
    name: 'Year-Round Gamer',   desc: 'Play a game on every single day of a calendar year',
    check: { type: 'played_every_day_of_year' } },
  { id: 'm_cal_sevens',  icon: '7️⃣', tier: 'silver', pts: 30,  category: 'seasonal',
    name: 'Lucky Sevens',       desc: 'Play a game on the 7th, 17th, and 27th of every month',
    check: { type: 'played_days_containing_digit', digit: 7 } },
  { id: 'ms_month_all',   icon: '📆', tier: 'gold',   pts: 60,  category: 'seasonal',
    name: 'Monthly Completionist', desc: 'Play every tracked game at least once in a calendar month',
    check: { type: 'all_games_in_month' } },
  { id: 'ms_3_wins_day',  icon: '☀️',  tier: 'gold',   pts: 45,  category: 'seasonal',
    name: 'Big Day',            desc: 'Win 3 different games in a single day',
    check: { type: 'n_different_games_won_same_day', count: 3 } },
];
