// ── planetunknown ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
// ── Planet Unknown ───────────────────────────────────────────
  {
    id: 'planetunknown', name: 'Planet Unknown', personalBestField: 'score', personalBestContext: 'planet', personalBestTitle: 'Best Score by Planet', icon: '🪐', genre: 'Polyomino · Tile Laying · Sci-Fi',
    color: '#4a2a8a', bgColor: '#f6f0ff', dimColor: '#9a70e0',
    logFields: [
      { id: 'win',         label: 'Win?',              type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'score',       label: 'Final Score',        type: 'number', min: 0,  max: 120, default: 55 },
      { id: 'targetScore', label: 'Target Score',       type: 'number', min: 0,  max: 90,  default: 60 },
      { id: 'planet',      label: 'Planet',             type: 'select', options: ['Unknown','KSB-4156','K-273','Gaia','Persphone','Arashi','Petra','Tartarus','Charybdis','Kaax','Pajitnov','Oblivion','Cerberus','Lacuna'] },
      { id: 'corporation', label: 'Corporation',        type: 'select', options: ['Unknown','Universal Coalition','Republic', 'Wormhole Corp.', 'Cosmos Inc.', 'Horizon Group','Jump Drive', 'Oasis Ultd.', 'Makeshift', 'Flux Industries'] },
      { id: 'asymmetric', label: 'Asymmetric combo?', type: 'toggle', trueLabel: 'Yes', falseLabel: 'No' },
      { id: 'metObj',       label: 'Met Private Objective', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No' },
      { id: 'noMeteorites', label: 'No Meteorites Left',    type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No' },
      { id: 'planetScore',  label: 'Planet Score',          type: 'number', min: 0, max: 30, default: 0 },
      { id: 'resourceScore',label: 'Resource Tracks',       type: 'number', min: 0, max: 30, default: 0 },
      { id: 'lifepodScore', label: 'Lifepods',              type: 'number', min: 0, max: 20, default: 0 },
      { id: 'meteoriteScore',label:'Meteorite Points',      type: 'number', min: 0, max: 20, default: 0 },
      { id: 'civScore',     label: 'CIV Cards',             type: 'number', min: 0, max: 20, default: 0 },
      { id: 'objectiveScore',label:'Objectives',            type: 'number', min: 0, max: 15, default: 0 },
    ],
    achievements: [
      { id: 'pu_first',    icon: '🌟', tier: 'bronze', pts: 10,  name: 'First Colony',
        desc: 'Win your first game',
        check: { type: 'min_wins', count: 1 } },
      { id: 'pu_score60',  icon: '🌍', tier: 'bronze', pts: 10,  name: 'Target Cleared',
        desc: 'Score 60+ points',
        check: { type: 'win_field_gte', field: 'score', value: 60 } },
      { id: 'pu_score70',  icon: '🚀', tier: 'silver', pts: 20,  name: 'Efficient Colony',
        desc: 'Score 70+ points',
        check: { type: 'win_field_gte', field: 'score', value: 70 } },
      { id: 'pu_score80',  icon: '⭐', tier: 'gold',   pts: 35,  name: 'Thriving World',
        desc: 'Score 80+ points',
        check: { type: 'win_field_gte', field: 'score', value: 80 } },
      { id: 'pu_score90',  icon: '🌌', tier: 'gold',   pts: 50,  name: 'Perfect Terraforming',
        desc: 'Score 90+ points',
        check: { type: 'win_field_gte', field: 'score', value: 90 } },
      { id: 'pu_margin10', icon: '📈', tier: 'silver', pts: 20,  name: 'Exceeded Expectations',
        desc: 'Beat the target score by 10+',
        check: { type: 'win_field_beats_by', field: 'score', compareField: 'targetScore', margin: 10 } },
      { id: 'pu_margin20', icon: '🏆', tier: 'gold',   pts: 40,  name: 'Dominant Colonist',
        desc: 'Beat the target score by 20+',
        check: { type: 'win_field_beats_by', field: 'score', compareField: 'targetScore', margin: 20 } },
      { id: 'pu_asymmetric',icon:'🧬', tier: 'silver', pts: 20,  name: 'Advanced Setup',
        desc: 'Win using asymmetric sides for both planet and corporation',
        check: { type: 'win_with_toggle', field: 'asymmetric' } },
      { id: 'pu_objective',icon: '🎯', tier: 'silver', pts: 15,  name: 'Objective Met',
        desc: 'Win while meeting your private objective',
        check: { type: 'win_with_toggle', field: 'metObj' } },
      { id: 'pu_clean',    icon: '🧹', tier: 'gold',   pts: 30,  name: 'Clean Sweep',
        desc: 'Win with no meteorites remaining on your planet',
        check: { type: 'win_with_toggle', field: 'noMeteorites' } },
      { id: 'pu_4corps',   icon: '🏢', tier: 'gold',   pts: 40,  name: 'Corporate Diversity',
        desc: 'Win with 4 different corporations',
        check: { type: 'unique_win_values', field: 'corporation', count: 4 } },
      { id: 'pu_9corps',   icon: '🏢', tier: 'gold',   pts: 60,  name: 'Corporate Overlord',
        desc: 'Win with 9 different corporations',
        check: { type: 'unique_win_values', field: 'corporation', count: 9 } },
      { id: 'pu_4planets', icon: '🌏', tier: 'gold',   pts: 40,  name: 'Planetary Explorer',
        desc: 'Win on 4 different planets',
        check: { type: 'unique_win_values', field: 'planet', count: 4 } },
      { id: 'pu_10plays',  icon: '🎮', tier: 'silver', pts: 20,  name: 'Seasoned Colonist',
        desc: 'Play 10 games',
        check: { type: 'min_plays', count: 10 } },
      { id: 'pu_plat',     icon: '💎', tier: 'plat',   pts: 100, name: 'Planet Master',
        desc: 'Unlock all other Planet Unknown achievements',
        check: { type: 'all_achievements', ids: [
          'pu_first','pu_score60','pu_score70','pu_score80','pu_score90',
          'pu_margin10','pu_margin20','pu_asymmetric','pu_objective',
          'pu_clean','pu_4corps','pu_4planets','pu_9corps','pu_10plays'
        ]}},
    ]
  }
);
