// ── skyteam ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
{
  id: 'skyteam',
  name: 'Sky Team',
  icon: '✈️',
  genre: 'Aviation',
  bggId: 373106,
  color: '#3dd1cf',
  logFields: [
    { id: 'win', label: 'Win?', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
    { id: 'scenario', label: 'Scenario', type: 'select', options: ['YUL (Green)', 'LHR (Green)', 'HND (Green)', 'OSL (Green)', 'ATL (Green)', 'PRG (Green)', 'CTP (Green ✈)', 'SYD (Green ✈)', 'PEK (Green ✈)', 'LHR (Yellow)', 'TGU (Yellow)', 'GIG (Yellow)', 'KEF (Yellow)', 'PRG (Yellow)', 'KUL (Yellow)', 'ATL (Yellow)', 'KBP (Yellow ✈)', 'TER (Yellow ✈)', 'SXM (Yellow ✈)', 'DUS (Yellow ✈)', 'MAD (Yellow ✈)', 'WAW (Yellow ✈)', 'PBH (Red)', 'HND (Red)', 'GIG (Red)', 'OSL (Red)', 'TGU (Red)', 'SXM (Red ✈)', 'SYD (Red ✈)', 'WAW (Red ✈)', 'DUS (Red ✈)', 'NZIR (Red ✈)', 'PEK (Red ✈)', 'KEF (Black)', 'KUL (Black)', 'PBH (Black)', 'CPT (Black ✈)', 'MAD (Black ✈)', 'TER (Black ✈)', 'KBP (Black ✈)', 'NZIR (Black ✈)'] },
    { id: 'role', label: 'Your Role', type: 'select', options: ['Pilot', 'Copilot', 'Solo'] },
    { id: 'coffeeCups',  label: 'Landed with three cups of coffee?', type: 'toggle' },
    { id: 'defeatCause', label: 'Defeat Cause', type: 'select',
      options: ['Mandatory Actions','Going into a Spin','Collision','Overshoot','Crash Landing','Airplane Tokens','Flaps & Landing Gear','Axis','Speed','Turns'],
      showIf: { field: 'win', value: false } },
  ],

  customStatsTitle: 'Airport Stats',
  customStats: [
    { label: 'YUL (Green)',  type: 'ratio', field: 'scenario', value: 'YUL (Green)' },
    { label: 'LHR (Green)',  type: 'ratio', field: 'scenario', value: 'LHR (Green)' },
    { label: 'HND (Green)',  type: 'ratio', field: 'scenario', value: 'HND (Green)' },
    { label: 'OSL (Green)',  type: 'ratio', field: 'scenario', value: 'OSL (Green)' },
    { label: 'ATL (Green)',  type: 'ratio', field: 'scenario', value: 'ATL (Green)' },
    { label: 'PRG (Green)',  type: 'ratio', field: 'scenario', value: 'PRG (Green)' },
    { label: 'LHR (Yellow)', type: 'ratio', field: 'scenario', value: 'LHR (Yellow)' },
    { label: 'TGU (Yellow)', type: 'ratio', field: 'scenario', value: 'TGU (Yellow)' },
    { label: 'GIG (Yellow)', type: 'ratio', field: 'scenario', value: 'GIG (Yellow)' },
    { label: 'KEF (Yellow)', type: 'ratio', field: 'scenario', value: 'KEF (Yellow)' },
    { label: 'PRG (Yellow)', type: 'ratio', field: 'scenario', value: 'PRG (Yellow)' },
    { label: 'KUL (Yellow)', type: 'ratio', field: 'scenario', value: 'KUL (Yellow)' },
    { label: 'ATL (Yellow)', type: 'ratio', field: 'scenario', value: 'ATL (Yellow)' },
    { label: 'PBH (Red)',    type: 'ratio', field: 'scenario', value: 'PBH (Red)' },
    { label: 'HND (Red)',    type: 'ratio', field: 'scenario', value: 'HND (Red)' },
    { label: 'GIG (Red)',    type: 'ratio', field: 'scenario', value: 'GIG (Red)' },
    { label: 'OSL (Red)',    type: 'ratio', field: 'scenario', value: 'OSL (Red)' },
    { label: 'TGU (Red)',    type: 'ratio', field: 'scenario', value: 'TGU (Red)' },
    { label: 'KEF (Black)',  type: 'ratio', field: 'scenario', value: 'KEF (Black)' },
    { label: 'KUL (Black)',  type: 'ratio', field: 'scenario', value: 'KUL (Black)' },
    { label: 'PBH (Black)',  type: 'ratio', field: 'scenario', value: 'PBH (Black)' },
  ],

  customStats2Title: 'Defeat Causes',
  customStats2: [
    { label: 'Mandatory Actions',    type: 'count_where', field: 'defeatCause', value: 'Mandatory Actions' },
    { label: 'Going into a Spin',    type: 'count_where', field: 'defeatCause', value: 'Going into a Spin' },
    { label: 'Collision',            type: 'count_where', field: 'defeatCause', value: 'Collision' },
    { label: 'Overshoot',            type: 'count_where', field: 'defeatCause', value: 'Overshoot' },
    { label: 'Crash Landing',        type: 'count_where', field: 'defeatCause', value: 'Crash Landing' },
    { label: 'Airplane Tokens',      type: 'count_where', field: 'defeatCause', value: 'Airplane Tokens' },
    { label: 'Flaps & Landing Gear', type: 'count_where', field: 'defeatCause', value: 'Flaps & Landing Gear' },
    { label: 'Axis',                 type: 'count_where', field: 'defeatCause', value: 'Axis' },
    { label: 'Speed',                type: 'count_where', field: 'defeatCause', value: 'Speed' },
    { label: 'Turns',                type: 'count_where', field: 'defeatCause', value: 'Turns' },
  ],
  completenessFields: ['scenario'],

  achievements: [
    { id: 'sky_caffeinated', icon: '☕', tier: 'bronze', pts: 10,
      name: 'Fully Caffeinated',
      desc: 'Land at an airport with three cups of coffee',
      check: { type: 'win_with_toggle', field: 'coffeeCups' } },
    { id: 'sky_base_green', icon: '🏆', tier: 'bronze', pts: 10,
      name: 'Student Pilot',
      desc: 'Land at all the base green airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['YUL (Green)', 'LHR (Green)', 'HND (Green)', 'OSL (Green)', 'ATL (Green)', 'PRG (Green)'] } },
    { id: 'sky_turb_green', icon: '🏆', tier: 'bronze', pts: 10,
      name: 'Private Pilot',
      desc: 'Land at all the Turbulence green airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['CTP (Green ✈)', 'SYD (Green ✈)', 'PEK (Green ✈)'] } },
    { id: 'sky_base_yellow', icon: '🏆', tier: 'silver', pts: 20,
      name: 'Instrument Rated',
      desc: 'Land at all the base yellow airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['LHR (Yellow)', 'TGU (Yellow)', 'GIG (Yellow)', 'KEF (Yellow)', 'PRG (Yellow)', 'KUL (Yellow)', 'ATL (Yellow)'] } },
    { id: 'sky_turb_yellow', icon: '🏆', tier: 'silver', pts: 20,
      name: 'Commercial CoPilot',
      desc: 'Land at all the Turbulence yellow airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['KBP (Yellow ✈)', 'TER (Yellow ✈)', 'SXM (Yellow ✈)', 'DUS (Yellow ✈)', 'MAD (Yellow ✈)', 'WAW (Yellow ✈)'] } },
    { id: 'sky_base_red', icon: '🏆', tier: 'silver', pts: 30,
      name: 'Certified Flight Instructor',
      desc: 'Land at all the base red airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['PBH (Red)', 'HND (Red)', 'GIG (Red)', 'OSL (Red)', 'TGU (Red)'] } },
    { id: 'sky_turb_red', icon: '🏆', tier: 'silver', pts: 30,
      name: 'Commercial Pilot',
      desc: 'Land at all the Turbulence red airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['SXM (Red ✈)', 'SYD (Red ✈)', 'WAW (Red ✈)', 'DUS (Red ✈)', 'NZIR (Red ✈)', 'PEK (Red ✈)'] } },
    { id: 'sky_base_black', icon: '🏆', tier: 'gold', pts: 50,
      name: 'Captain',
      desc: 'Land at all base black airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['KEF (Black)', 'KUL (Black)', 'PBH (Black)'] } },
    { id: 'sky_turb_black', icon: '🏆', tier: 'gold', pts: 50,
      name: 'Chief Pilot',
      desc: 'Land at all Turbulence black airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['CPT (Black ✈)', 'MAD (Black ✈)', 'TER (Black ✈)', 'KBP (Black ✈)', 'NZIR (Black ✈)'] } },
    { id: 'sky_frequent_crasher', icon: '💥', tier: 'gold', pts: 40,
      name: 'Frequent Crasher',
      desc: 'Lose in all 10 different ways',
      check: { type: 'unique_values', field: 'defeatCause', count: 10 } },
    { id: 'sky_all_airports', icon: '🏆', tier: 'plat', pts: 100,
      name: 'Legend of the Skies',
      desc: 'Land at Every Airport',
      check: { type: 'win_all_values', field: 'scenario', values: ['YUL (Green)', 'LHR (Green)', 'HND (Green)', 'OSL (Green)', 'ATL (Green)', 'PRG (Green)', 'CTP (Green ✈)', 'SYD (Green ✈)', 'PEK (Green ✈)', 'LHR (Yellow)', 'TGU (Yellow)', 'GIG (Yellow)', 'KEF (Yellow)', 'PRG (Yellow)', 'KUL (Yellow)', 'ATL (Yellow)', 'KBP (Yellow ✈)', 'TER (Yellow ✈)', 'SXM (Yellow ✈)', 'DUS (Yellow ✈)', 'MAD (Yellow ✈)', 'WAW (Yellow ✈)', 'PBH (Red)', 'HND (Red)', 'GIG (Red)', 'OSL (Red)', 'TGU (Red)', 'SXM (Red ✈)', 'SYD (Red ✈)', 'WAW (Red ✈)', 'DUS (Red ✈)', 'NZIR (Red ✈)', 'PEK (Red ✈)', 'KEF (Black)', 'KUL (Black)', 'PBH (Black)', 'CPT (Black ✈)', 'MAD (Black ✈)', 'TER (Black ✈)', 'KBP (Black ✈)', 'NZIR (Black ✈)'] } },

  ]
}
);
