// ── skyteam ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
{
  id: 'skyteam',
  name: 'Sky Team',
  icon: '✈️',
  genre: 'Aviation',
  bggId: 373106,
  color: '#3dd1cf',
  logFields: [
    { id: 'win', label: 'Win?', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
    { id: 'scenario', label: 'Scenario', type: 'select', options: ['YUL (Green)', 'LHR (Green)', 'HND (Green)', 'OSL (Green)', 'ATL (Green)', 'PRG (Green)', 'CTP (Green ✈)', 'SYD (Green ✈)', 'PEK (Green ✈)', 'LHR (Yellow)', 'TGU (Yellow)', 'GIG (Yellow)', 'KEF (Yellow)', 'PRG (Yellow)', 'KUL (Yellow)', 'ATL (Yellow)', 'KBP (Yellow ✈)', 'TER (Yellow ✈)', 'SXM (Yellow ✈)', 'DUS (Yellow ✈)', 'MAD (Yellow ✈)', 'WAW (Yellow ✈)', 'PBH (Red)', 'HND (Red)', 'GIG (Red)', 'OSL (Red)', 'TGU (Red)', 'SXM (Red ✈)', 'SYD (Red ✈)', 'WAW (Red ✈)', 'DUS (Red ✈)', 'NZIR (Red ✈)', 'PEK (Red ✈)', 'KEF (Black)', 'KUL (Black)', 'PBH (Black)', 'CPT (Black ✈)', 'MAD (Black ✈)', 'TER (Black ✈)', 'KBP (Black ✈)', 'NZIR (Black ✈)'] },
    { id: 'coffeeCups', label: 'Landed with three cups of coffee?', type: 'toggle' },
  ],
  achievements: [
    { id: 'sky_caffeinated', icon: '☕', tier: 'bronze', pts: 10,
      name: 'Fully Caffeinated',
      desc: 'Land at an airport with three cups of coffee',
      check: { type: 'win_with_toggle', field: 'coffeeCups' } },
    { id: 'sky_base_green', icon: '🏆', tier: 'bronze', pts: 10,
      name: 'Student Pilot',
      desc: 'Land at all the base green airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['YUL (Green)', 'LHR (Green)', 'HND (Green)', 'OSL (Green)', 'ATL (Green)', 'PRG (Green)'] } },
    { id: 'sky_turb_green', icon: '🏆', tier: 'bronze', pts: 10,
      name: 'Private Pilot',
      desc: 'Land at all the Turbulence green airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['CTP (Green ✈)', 'SYD (Green ✈)', 'PEK (Green ✈)'] } },
    { id: 'sky_base_yellow', icon: '🏆', tier: 'silver', pts: 20,
      name: 'Instrument Rated',
      desc: 'Land at all the base yellow airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['LHR (Yellow)', 'TGU (Yellow)', 'GIG (Yellow)', 'KEF (Yellow)', 'PRG (Yellow)', 'KUL (Yellow)', 'ATL (Yellow)'] } },
    { id: 'sky_turb_yellow', icon: '🏆', tier: 'silver', pts: 20,
      name: 'Commercial CoPilot',
      desc: 'Land at all the Turbulence yellow airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['KBP (Yellow ✈)', 'TER (Yellow ✈)', 'SXM (Yellow ✈)', 'DUS (Yellow ✈)', 'MAD (Yellow ✈)', 'WAW (Yellow ✈)'] } },
    { id: 'sky_base_red', icon: '🏆', tier: 'silver', pts: 30,
      name: 'Certified Flight Instructor',
      desc: 'Land at all the base red airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['PBH (Red)', 'HND (Red)', 'GIG (Red)', 'OSL (Red)', 'TGU (Red)'] } },
    { id: 'sky_turb_red', icon: '🏆', tier: 'silver', pts: 30,
      name: 'Commercial Pilot',
      desc: 'Land at all the Turbulence red airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['SXM (Red ✈)', 'SYD (Red ✈)', 'WAW (Red ✈)', 'DUS (Red ✈)', 'NZIR (Red ✈)', 'PEK (Red ✈)'] } },
    { id: 'sky_base_black', icon: '🏆', tier: 'gold', pts: 50,
      name: 'Captain',
      desc: 'Land at all base black airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['KEF (Black)', 'KUL (Black)', 'PBH (Black)'] } },
    { id: 'sky_turb_black', icon: '🏆', tier: 'gold', pts: 50,
      name: 'Chief Pilot',
      desc: 'Land at all Turbulence black airports',
      check: { type: 'win_all_values', field: 'scenario', values: ['CPT (Black ✈)', 'MAD (Black ✈)', 'TER (Black ✈)', 'KBP (Black ✈)', 'NZIR (Black ✈)'] } },
    { id: 'sky_all_airports', icon: '🏆', tier: 'plat', pts: 100,
      name: 'Legend of the Skies',
      desc: 'Land at Every Airport',
      check: { type: 'win_all_values', field: 'scenario', values: ['YUL (Green)', 'LHR (Green)', 'HND (Green)', 'OSL (Green)', 'ATL (Green)', 'PRG (Green)', 'CTP (Green ✈)', 'SYD (Green ✈)', 'PEK (Green ✈)', 'LHR (Yellow)', 'TGU (Yellow)', 'GIG (Yellow)', 'KEF (Yellow)', 'PRG (Yellow)', 'KUL (Yellow)', 'ATL (Yellow)', 'KBP (Yellow ✈)', 'TER (Yellow ✈)', 'SXM (Yellow ✈)', 'DUS (Yellow ✈)', 'MAD (Yellow ✈)', 'WAW (Yellow ✈)', 'PBH (Red)', 'HND (Red)', 'GIG (Red)', 'OSL (Red)', 'TGU (Red)', 'SXM (Red ✈)', 'SYD (Red ✈)', 'WAW (Red ✈)', 'DUS (Red ✈)', 'NZIR (Red ✈)', 'PEK (Red ✈)', 'KEF (Black)', 'KUL (Black)', 'PBH (Black)', 'CPT (Black ✈)', 'MAD (Black ✈)', 'TER (Black ✈)', 'KBP (Black ✈)', 'NZIR (Black ✈)'] } },

  ]
}
);
