// ── sprawlopolis ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
// ── Sprawlopolis ──────────────────────────────────────────────
  {
    id: 'sprawlopolis', name: 'Sprawlopolis', icon: '🏙️', genre: 'Card Placement · City Building',
    color: '#3a6a9a', bgColor: '#f0f6ff', dimColor: '#80b0e0',
    logFields: [
      { id: 'win',        label: 'Win?',          type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'scoringCards', label: 'Scoring Cards (pick 3)', type: 'cards', count: 3, noun: 'scoring cards',
        targets: ['card1','card2','card3'], sumTo: 'targetScore', sumDefault: 9, options: [
          '01 The Outskirts','02 Bloom Boom','03 Go Green','04 Block Party','05 Stacks and Scrapers','06 Master Planned',
          '07 Central Perks','08 The \'Burbs','09 Concrete Jungle','10 The Strip','11 Mini Marts','12 The Superhighway',
          '13 Park Hopping','14 Looping Lanes','15 Skid Row','16 Morning Commute','17 Tourist Traps','18 Sprawlopolis'
        ] },
      { id: 'cardPoints', label: 'Points per scoring card', type: 'cardpoints', targets: ['cpts1','cpts2','cpts3'], sumTo: 'sheet_scoring' },
      { id: 'sheet_residential', label: 'Residential (largest)', type: 'number', min: 0, max: 60, default: '', scorePart: 'add' },
      { id: 'sheet_commercial',  label: 'Commercial (largest)',  type: 'number', min: 0, max: 60, default: '', scorePart: 'add' },
      { id: 'sheet_industrial',  label: 'Industrial (largest)',  type: 'number', min: 0, max: 60, default: '', scorePart: 'add' },
      { id: 'sheet_park',        label: 'Park (largest)',        type: 'number', min: 0, max: 60, default: '', scorePart: 'add' },
      { id: 'sheet_roadtax',     label: 'Road tax (unfinished roads)', type: 'number', min: 0, max: 60, default: '', scorePart: 'sub' },
      { id: 'score',      label: 'Final Score',   type: 'number', min: -60, max: 120, default: 0, derived: true },
    ],
    completenessFields: ['card1'],

    customStatsTitle: 'Scoring Card Win Rate',
    customStats: [
      { label: '01 The Outskirts',    type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'The Outskirts' },
      { label: '02 Bloom Boom',       type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Bloom Boom' },
      { label: '03 Go Green',         type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Go Green' },
      { label: '04 Block Party',      type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Block Party' },
      { label: '07 Central Perks',    type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Central Perks' },
      { label: '10 The Strip',        type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'The Strip' },
      { label: '12 The Superhighway', type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'The Superhighway' },
      { label: '13 Park Hopping',     type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Park Hopping' },
      { label: '14 Looping Lanes',    type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Looping Lanes' },
      { label: '15 Skid Row',         type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Skid Row' },
      { label: '16 Morning Commute',  type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Morning Commute' },
      { label: '17 Tourist Traps',    type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Tourist Traps' },
      { label: '18 Sprawlopolis',     type: 'ratio_any_field', fields: ['card1','card2','card3'], value: 'Sprawlopolis' },
    ],

    customStats2Title: 'Score Breakdown (avg per game)',
    customStats2: [
      { label: 'Scoring conditions', type: 'avg', field: 'sheet_scoring', presentOnly: true },
      { label: 'Residential',        type: 'avg', field: 'sheet_residential', presentOnly: true },
      { label: 'Commercial',         type: 'avg', field: 'sheet_commercial', presentOnly: true },
      { label: 'Industrial',         type: 'avg', field: 'sheet_industrial', presentOnly: true },
      { label: 'Park',               type: 'avg', field: 'sheet_park', presentOnly: true },
      { label: 'Road tax (lost)',    type: 'avg', field: 'sheet_roadtax', presentOnly: true, negative: true },
    ],

    achievements: [
      { id: 'sp_allcards', icon: '🗂️', tier: 'plat', pts: 60, name: 'City Planner Supreme',
        desc: 'Win at least once with every scoring card',
        check: { type: 'win_all_values_multifield', fields: ['card1','card2','card3'], values: [
          'The Outskirts','Bloom Boom','Go Green','Block Party','Stacks and Scrapers','Master Planned',
          'Central Perks','The \'Burbs','Concrete Jungle','The Strip','Mini Marts','The Superhighway',
          'Park Hopping','Looping Lanes','Skid Row','Morning Commute','Tourist Traps','Sprawlopolis'
        ] } },
      { id: 'sp_allcombos', icon: '💠', tier: 'diamond', pts: 150, name: 'The Whole Sprawl',
        desc: 'Win with every possible 3-card scoring combination (816 in all)',
        check: { type: 'win_all_combos_multifield', fields: ['card1','card2','card3'], values: [
          'The Outskirts','Bloom Boom','Go Green','Block Party','Stacks and Scrapers','Master Planned',
          'Central Perks','The \'Burbs','Concrete Jungle','The Strip','Mini Marts','The Superhighway',
          'Park Hopping','Looping Lanes','Skid Row','Morning Commute','Tourist Traps','Sprawlopolis'
        ] } },
      { id: 'sp_cleanroads', icon: '🛣️', tier: 'silver', pts: 20, name: 'Clean Streets',
        desc: 'Win with 2 or fewer road-tax points lost',
        check: { type: 'win_field_lte', field: 'sheet_roadtax', value: 2 } },
      { id: 'sp_bigscoring', icon: '🎴', tier: 'silver', pts: 20, name: 'Optimal Draw',
        desc: 'Win a game where your scoring cards total 40+ points',
        check: { type: 'win_field_gte', field: 'sheet_scoring', value: 40 } },
      { id: 'sp_card18', icon: '🃏', tier: 'gold', pts: 25, name: 'The Eighteenth Card',
        desc: 'Win a game that includes the "Sprawlopolis" scoring card',
        check: { type: 'win_with_any_field', fields: ['card1','card2','card3'], value: 'Sprawlopolis' } },
      { id: 'sp_first',    icon: '🌟', tier: 'bronze', pts: 10,  name: 'First District',
        desc: 'Win your first game',
        check: { type: 'min_wins', count: 1 } },
      { id: 'sp_score30',  icon: '📐', tier: 'bronze', pts: 10,  name: 'Decent Layout',
        desc: 'Score 30+ points in any game',
        check: { type: 'field_gte', field: 'score', value: 30 } },
      { id: 'sp_score50',  icon: '🏗️', tier: 'silver', pts: 20,  name: 'Well Planned',
        desc: 'Score 50+ points in any game',
        check: { type: 'field_gte', field: 'score', value: 50 } },
      { id: 'sp_score65',  icon: '🌆', tier: 'gold',   pts: 40,  name: 'Grand City',
        desc: 'Score 65+ points in any game',
        check: { type: 'field_gte', field: 'score', value: 65 } },
      { id: 'sp_margin5',  icon: '📈', tier: 'silver', pts: 20,  name: 'Clear Victory',
        desc: 'Beat the target score by 5+',
        check: { type: 'win_field_beats_by', field: 'score', compareField: 'targetScore', margin: 5 } },
      { id: 'sp_margin10', icon: '🏅', tier: 'gold',   pts: 35,  name: 'Dominant Planning',
        desc: 'Beat the target score by 10+',
        check: { type: 'win_field_beats_by', field: 'score', compareField: 'targetScore', margin: 10 } },
      { id: 'sp_margin15', icon: '🏆', tier: 'gold',   pts: 50,  name: 'Masterwork',
        desc: 'Beat the target score by 15+',
        check: { type: 'win_field_beats_by', field: 'score', compareField: 'targetScore', margin: 15 } },
      { id: 'sp_hightarget',icon:'🎯', tier: 'gold',   pts: 40,  name: 'Hard Cards',
        desc: 'Win with a target score of 40+',
        check: { type: 'win_two_fields_gte', field1: 'targetScore', value1: 40, field2: 'score', value2: 0 } },
      { id: 'sp_5wins',    icon: '🏙️', tier: 'silver', pts: 25,  name: 'Urban Planner',
        desc: 'Win 5 games',
        check: { type: 'min_wins', count: 5 } },
      { id: 'sp_10wins',   icon: '🌇', tier: 'gold',   pts: 35,  name: 'City Architect',
        desc: 'Win 10 games',
        check: { type: 'min_wins', count: 10 } },
      { id: 'sp_15plays',  icon: '🎮', tier: 'silver', pts: 20,  name: 'City Regular',
        desc: 'Play 15 games',
        check: { type: 'min_plays', count: 15 } },
      { id: 'sp_plat',     icon: '💎', tier: 'plat',   pts: 100, name: 'Master Planner',
        desc: 'Unlock all other Sprawlopolis achievements',
        check: { type: 'all_achievements', ids: ['sp_first','sp_score30','sp_score50','sp_score65','sp_margin5','sp_margin10','sp_margin15','sp_hightarget','sp_5wins','sp_10wins','sp_15plays'] } },
    ]
  }
);
