// BGStats comment tags: [decksize=N] [relics=N]
// Use [key=?] if you tracked it but didn't record the value
// ── sts ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
// ── Slay the Spire: The Board Game ───────────────────────────
  {
    id:       'sts',
    name:     'Slay the Spire: TBG',
    icon:     '⚔️',
    genre:    'Deckbuilding · Roguelike',
    color:    '#c0392b',
    bgColor:  '#fff5f5',
    dimColor: '#e8a0a0',

    logFields: [
      { id: 'win',        label: 'Win?',           type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'character',  label: 'Character',      type: 'select', options: ['— Select —','Ironclad','Silent','Defect','Watcher'] },
      { id: 'character2', label: 'Character 2',    type: 'select', options: ['None','Ironclad','Silent','Defect','Watcher'] },
      { id: 'character3', label: 'Character 3',    type: 'select', options: ['None','Ironclad','Silent','Defect','Watcher'] },
      { id: 'character4', label: 'Character 4',    type: 'select', options: ['None','Ironclad','Silent','Defect','Watcher'] },
      { id: 'actsCleared', label: 'Acts Cleared',  type: 'select', options: ['— Select —','Act 1','Act 2','Act 3','Act 4'] },
      { id: 'boss',       label: 'Boss Fought',   type: 'select', options: [
        'None',
        'The Guardian','Slime Boss','Hexaghost',
        'The Champ','Bronze Automaton','The Collector',
        'The Awakened One','Time Eater','Donu & Deca',
        'The Corrupt Heart'
      ] },
      { id: 'ascension',  label: 'Ascension Level',type: 'number', min: 0, max: 13, default: 0 },
      { id: 'playerCount',label: 'Player Count',   type: 'number', min: 1, max: 4, default: 1 },
      { id: 'deckSize',   label: 'Final Deck Size', type: 'number', min: 0, max: 30, default: 0 },
      { id: 'relicCount', label: 'Relics Held',     type: 'number', min: 0, max: 20, default: 3 },
      { id: 'hpFull',     label: 'All Players at Full HP (boss kill)', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'noRares',    label: 'No Uncommons or Rares in deck', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'noRelics',   label: 'No Relics or Boss Relics',      type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'dailyClimb', label: 'Daily Climb run',               type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'bossT1',     label: 'Defeated Boss on Turn 1',       type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'hitStrength',label: 'Hit Strength Limit (8)',        type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'hitPoison',  label: 'Hit Poison Limit (30)',         type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'hitBlock',   label: 'Hit Block Limit (20)',          type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'play7shivs', label: 'Played 7 Shivs in One Turn',   type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'have7powers',label: '7 Powers in Play at Once',      type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'killedTransient', label: 'Killed The Transient in Time', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'infiniteCombo',   label: 'Created Infinite Combo',      type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
    ],

    customStatsTitle: 'Player Count',
    customStats: [
      { label: 'Solo (1p)',  type: 'ratio', field: 'playerCount', value: 1 },
      { label: '2 Players',  type: 'ratio', field: 'playerCount', value: 2 },
      { label: '3 Players',  type: 'ratio', field: 'playerCount', value: 3 },
      { label: '4 Players',  type: 'ratio', field: 'playerCount', value: 4 },
    ],

    customStats2Title: 'Character Win Rate',
    customStats2: [
      { label: 'Ironclad', type: 'ratio', field: 'character', value: 'Ironclad' },
      { label: 'Silent',   type: 'ratio', field: 'character', value: 'Silent' },
      { label: 'Defect',   type: 'ratio', field: 'character', value: 'Defect' },
      { label: 'Watcher',  type: 'ratio', field: 'character', value: 'Watcher' },
    ],

    customStats3Title: 'Acts Cleared',
    customStats4: [
      { label: 'Act 1', type: 'ratio', field: 'actsCleared', value: 'Act 1' },
      { label: 'Act 2', type: 'ratio', field: 'actsCleared', value: 'Act 2' },
      { label: 'Act 3', type: 'ratio', field: 'actsCleared', value: 'Act 3' },
      { label: 'Act 4', type: 'ratio', field: 'actsCleared', value: 'Act 4' },
    ],

    customStats4Title: 'Boss Win Rate',
    customStats3: [
      { label: 'The Guardian',     type: 'ratio', field: 'boss', value: 'The Guardian' },
      { label: 'Slime Boss',       type: 'ratio', field: 'boss', value: 'Slime Boss' },
      { label: 'Hexaghost',        type: 'ratio', field: 'boss', value: 'Hexaghost' },
      { label: 'The Champ',        type: 'ratio', field: 'boss', value: 'The Champ' },
      { label: 'Bronze Automaton', type: 'ratio', field: 'boss', value: 'Bronze Automaton' },
      { label: 'The Collector',    type: 'ratio', field: 'boss', value: 'The Collector' },
      { label: 'The Awakened One',     type: 'ratio', field: 'boss', value: 'The Awakened One' },
      { label: 'Time Eater',       type: 'ratio', field: 'boss', value: 'Time Eater' },
      { label: 'Donu & Deca',      type: 'ratio', field: 'boss', value: 'Donu & Deca' },
      { label: 'The Corrupt Heart',type: 'ratio', field: 'boss', value: 'The Corrupt Heart' },
    ],

    completenessFields: ['character', 'actsCleared'],

    achievements: [
      // ── Character wins (official) ──
      { id: 'sts_ruby', official: true,      icon: '❤️',  tier: 'bronze', pts: 15, name: 'Ruby',
        desc: 'Beat Act III with the Ironclad',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Ironclad', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_emerald', official: true,   icon: '💚', tier: 'bronze', pts: 15, name: 'Emerald',
        desc: 'Beat Act III with the Silent',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Silent', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_sapphire', official: true,  icon: '💙', tier: 'bronze', pts: 15, name: 'Sapphire',
        desc: 'Beat Act III with the Defect',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Defect', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_amethyst', official: true,  icon: '💜', tier: 'bronze', pts: 15, name: 'Amethyst',
        desc: 'Beat Act III with the Watcher',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Watcher', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_all_chars', official: true, icon: '✨', tier: 'gold',   pts: 40, name: 'Full Roster',
        desc: 'Beat Act III with all 4 characters',
        check: { type: 'all_achievements', ids: ['sts_ruby','sts_emerald','sts_sapphire','sts_amethyst'] } },

      // ── Ascension milestones ──
      { id: 'sts_asc1',      icon: '🔥', tier: 'bronze', pts: 10, name: 'Ascension Unlocked',
        desc: 'Unlock Ascension mode (beat Act II boss solo / Act III with 2+ players)',
        check: { type: 'field_gte', field: 'ascension', value: 1 } },
      { id: 'sts_asc5',      icon: '🔥', tier: 'silver', pts: 20, name: 'Ascending',
        desc: 'Reach Ascension 5',
        check: { type: 'field_gte', field: 'ascension', value: 5 } },
      { id: 'sts_asc10',     icon: '🔥', tier: 'gold',   pts: 35, name: 'High Climber',
        desc: 'Complete Ascension Level 10',
        check: { type: 'win_field_gte', field: 'ascension', value: 10 } },
      { id: 'sts_asc13',     icon: '🔥', tier: 'gold',   pts: 60, name: 'Double Act 3 Boss',
        desc: 'Complete Ascension Level 13',
        check: { type: 'win_field_gte', field: 'ascension', value: 13 } },

      // ── Official achievements (from rulebook) ──
      { id: 'sts_jaxxed', official: true,    icon: '💪', tier: 'silver', pts: 20, name: 'Jaxxed',
        desc: 'Hit the Strength limit (8)',
        check: { type: 'win_with_toggle', field: 'hitStrength' } },
      { id: 'sts_catalyst', official: true,  icon: '☠️',  tier: 'silver', pts: 20, name: 'Catalyst',
        desc: 'Hit the Poison limit (30)',
        check: { type: 'win_with_toggle', field: 'hitPoison' } },
      { id: 'sts_ninja', official: true,     icon: '🗡️', tier: 'silver', pts: 25, name: 'Ninja',
        desc: 'Play 7 Shivs in one turn',
        check: { type: 'win_with_toggle', field: 'play7shivs' } },
      { id: 'sts_powerful', official: true,  icon: '⚡', tier: 'silver', pts: 20, name: 'Powerful',
        desc: 'Have 7 Powers in play at once',
        check: { type: 'win_with_toggle', field: 'have7powers' } },
      { id: 'sts_barricaded', official: true,icon: '🛡️', tier: 'silver', pts: 20, name: 'Barricaded',
        desc: 'Hit the Block limit (20)',
        check: { type: 'win_with_toggle', field: 'hitBlock' } },
      { id: 'sts_nothing', official: true,   icon: '⚡', tier: 'gold',   pts: 40, name: 'You Are Nothing',
        desc: 'Defeat a Boss on turn 1',
        check: { type: 'win_with_toggle', field: 'bossT1' } },
      { id: 'sts_perfect', official: true,   icon: '❤️',  tier: 'gold',   pts: 35, name: 'Perfect',
        desc: 'Beat a Boss with all players at full HP',
        check: { type: 'win_with_toggle', field: 'hpFull' } },
      { id: 'sts_minimalist', official: true,icon: '🃏', tier: 'gold',   pts: 50, name: 'Minimalist',
        desc: 'Beat Act III with a 5 card deck or smaller',
        check: { type: 'win_field_lte_and_field_eq', field: 'deckSize', value: 5, condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_transient', official: true, icon: '👻', tier: 'gold',   pts: 40, name: 'The Transient',
        desc: 'Kill The Transient before it kills itself',
        check: { type: 'win_with_toggle', field: 'killedTransient' } },
      { id: 'sts_common', official: true,    icon: '📦', tier: 'gold',   pts: 40, name: 'Common Sense',
        desc: 'Beat Act III with no uncommons or rares',
        check: { type: 'win_with_toggle_and_field_eq', field: 'noRares', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_collector', official: true, icon: '🎒', tier: 'gold',   pts: 35, name: 'Collector',
        desc: 'Beat Act III with 12+ relics and Boss relics per player',
        check: { type: 'win_field_gte_and_field_eq', field: 'relicCount', value: 12, condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_lucky', official: true,     icon: '🎲', tier: 'silver', pts: 20, name: 'My Lucky Day',
        desc: 'Beat Act III with a Daily Climb',
        check: { type: 'win_with_toggle_and_field_eq', field: 'dailyClimb', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_infinity', official: true,  icon: '♾️', tier: 'gold',   pts: 50, name: 'Infinity',
        desc: 'Create an infinite card combo',
        check: { type: 'win_with_toggle', field: 'infiniteCombo' } },
      { id: 'sts_norelics', official: true,  icon: '🚫', tier: 'gold',   pts: 45, name: 'Who Needs Relics?',
        desc: 'Beat Act III with no relics or Boss relics',
        check: { type: 'win_with_toggle_and_field_eq', field: 'noRelics', condField: 'actsCleared', condValue: 'Act 3' } },

      // ── Act beat milestones ──
      { id: 'sts_act1',  icon: '🗡️', tier: 'bronze', pts: 10, name: 'Act I Cleared',
        desc: 'Beat Act I',
        check: { type: 'win_with_field', field: 'actsCleared', value: 'Act 1' } },
      { id: 'sts_act2',  icon: '⚔️',  tier: 'silver', pts: 20, name: 'Act II Cleared',
        desc: 'Beat Act II',
        check: { type: 'win_with_field', field: 'actsCleared', value: 'Act 2' } },
      { id: 'sts_act4',  icon: '💀', tier: 'gold',   pts: 50, name: 'Act IV Cleared',
        desc: 'Beat Act IV (The Corrupt Heart)',
        check: { type: 'win_with_field', field: 'actsCleared', value: 'Act 4' } },

      // ── Boss defeats ──
      { id: 'sts_b_guardian',  icon: '🐉', tier: 'bronze', pts: 10, name: 'Guardian Slain',
        desc: 'Beat The Guardian',
        check: { type: 'win_with_field', field: 'boss', value: 'The Guardian' } },
      { id: 'sts_b_slime',     icon: '🟢', tier: 'bronze', pts: 10, name: 'Slimed',
        desc: 'Beat the Slime Boss',
        check: { type: 'win_with_field', field: 'boss', value: 'Slime Boss' } },
      { id: 'sts_b_hexaghost', icon: '👻', tier: 'bronze', pts: 10, name: 'Exorcised',
        desc: 'Beat Hexaghost',
        check: { type: 'win_with_field', field: 'boss', value: 'Hexaghost' } },
      { id: 'sts_b_champ',     icon: '🥊', tier: 'silver', pts: 15, name: 'Dethroned',
        desc: 'Beat The Champ',
        check: { type: 'win_with_field', field: 'boss', value: 'The Champ' } },
      { id: 'sts_b_automaton', icon: '🤖', tier: 'silver', pts: 15, name: 'Deactivated',
        desc: 'Beat The Automaton',
        check: { type: 'win_with_field', field: 'boss', value: 'Bronze Automaton' } },
      { id: 'sts_b_collector', icon: '🧳', tier: 'silver', pts: 15, name: 'Uncollected',
        desc: 'Beat The Collector',
        check: { type: 'win_with_field', field: 'boss', value: 'The Collector' } },
      { id: 'sts_b_awakened',  icon: '🌑', tier: 'gold',   pts: 25, name: 'Awakened No More',
        desc: 'Beat The Awakened One',
        check: { type: 'win_with_field', field: 'boss', value: 'The Awakened One' } },
      { id: 'sts_b_timeeater', icon: '⏳', tier: 'gold',   pts: 25, name: 'Time Stopped',
        desc: 'Beat Time Eater',
        check: { type: 'win_with_field', field: 'boss', value: 'Time Eater' } },
      { id: 'sts_b_donu',      icon: '🍩', tier: 'gold',   pts: 25, name: 'Dessert Denied',
        desc: 'Beat Donu & Deca',
        check: { type: 'win_with_field', field: 'boss', value: 'Donu & Deca' } },
      { id: 'sts_b_heart',     icon: '💔', tier: 'gold',   pts: 60, name: 'Heartbreaker',
        desc: 'Beat The Corrupt Heart',
        check: { type: 'win_with_field', field: 'boss', value: 'The Corrupt Heart' } },
      { id: 'sts_all_act1',    icon: '🏅', tier: 'silver', pts: 25, name: 'Act I Master',
        desc: 'Beat all three Act I bosses',
        check: { type: 'all_achievements', ids: ['sts_b_guardian','sts_b_slime','sts_b_hexaghost'] } },
      { id: 'sts_all_act2',    icon: '🏅', tier: 'gold',   pts: 35, name: 'Act II Master',
        desc: 'Beat all three Act II bosses',
        check: { type: 'all_achievements', ids: ['sts_b_champ','sts_b_automaton','sts_b_collector'] } },
      { id: 'sts_all_act3',    icon: '🏅', tier: 'gold',   pts: 50, name: 'Act III Master',
        desc: 'Beat all three Act III bosses',
        check: { type: 'all_achievements', ids: ['sts_b_awakened','sts_b_timeeater','sts_b_donu'] } },

      // ── Play milestones ──
      { id: 'sts_10plays',   icon: '🎮', tier: 'silver', pts: 20, name: 'Veteran Climber',
        desc: 'Play 10 runs total',
        check: { type: 'min_plays', count: 10 } },
      { id: 'sts_10wins',    icon: '🏆', tier: 'gold',   pts: 35, name: 'Spire Slayer',
        desc: 'Win 20 runs',
        check: { type: 'min_wins', count: 20 } },

      // ── Platinum ──
      { id: 'sts_plat',      icon: '💎', tier: 'plat',   pts: 100, name: 'Spire Conquered',
        desc: 'Unlock all other Slay the Spire achievements',
        check: { type: 'all_achievements', ids: [
          'sts_ruby','sts_emerald','sts_sapphire','sts_amethyst','sts_all_chars',
          'sts_asc1','sts_asc5','sts_asc10','sts_asc13',
          'sts_jaxxed','sts_catalyst','sts_ninja','sts_powerful','sts_barricaded',
          'sts_nothing','sts_perfect','sts_minimalist','sts_transient',
          'sts_common','sts_collector','sts_lucky','sts_infinity','sts_norelics',
          'sts_act1','sts_act2','sts_act4',
          'sts_all_act1','sts_all_act2','sts_all_act3','sts_b_heart',
          'sts_10plays','sts_10wins',
        ]}},
    ]
  }
);
