// ── sts ──
window.GAME_DEFINITIONS = window.GAME_DEFINITIONS || [];
window.GAME_DEFINITIONS.push(
// ── Slay the Spire: The Board Game ───────────────────────────
  {
    id:       'sts',
    name:     'Slay the Spire: TBG',
    personalBestField: 'character',
    icon:     '⚔️',
    genre:    'Deckbuilding · Roguelike',
    color:    '#c0392b',
    bgColor:  '#fff5f5',
    dimColor: '#e8a0a0',

    logFields: [
      { id: 'win',        label: 'Win?',           type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'character',  label: 'Character',      type: 'select', options: ['Ironclad','Silent','Defect','Watcher'] },
      { id: 'character2', label: 'Character 2',    type: 'select', options: ['None','Ironclad','Silent','Defect','Watcher'] },
      { id: 'character3', label: 'Character 3',    type: 'select', options: ['None','Ironclad','Silent','Defect','Watcher'] },
      { id: 'character4', label: 'Character 4',    type: 'select', options: ['None','Ironclad','Silent','Defect','Watcher'] },
      { id: 'actsCleared', label: 'Acts Cleared',  type: 'select', options: ['Act 1','Act 2','Act 3','Act 4'] },
      { id: 'ascension',  label: 'Ascension Level',type: 'number', min: 0, max: 13, default: 0 },
      { id: 'playerCount',label: 'Player Count',   type: 'number', min: 1, max: 4, default: 1 },
      { id: 'deckSize',   label: 'Final Deck Size', type: 'number', min: 1, max: 30, default: 10 },
      { id: 'relicCount', label: 'Relics Held',     type: 'number', min: 0, max: 20, default: 3 },
      { id: 'hpFull',     label: 'All Players at Full HP (boss kill)', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'noRares',    label: 'No Uncommons or Rares in deck', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'noRelics',   label: 'No Relics or Boss Relics',      type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'dailyClimb', label: 'Daily Climb run',               type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'bossT1',     label: 'Defeated Boss on Turn 1',       type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'hitStrength',label: 'Hit Strength Limit (8)',        type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'hitPoison',  label: 'Hit Poison Limit (30)',         type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'hitBlock',   label: 'Hit Block Limit (20)',          type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'play7shivs', label: 'Played 7 Shivs in One Turn',   type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'have7powers',label: '7 Powers in Play at Once',      type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'killedTransient', label: 'Killed The Transient in Time', type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
      { id: 'infiniteCombo',   label: 'Created Infinite Combo',      type: 'toggle', trueLabel: 'Yes ✓', falseLabel: 'No ✗' },
    ],

    achievements: [
      // ── Character wins (official) ──
      { id: 'sts_ruby', official: true,      icon: '❤️',  tier: 'bronze', pts: 15, name: 'Ruby',
        desc: 'Beat Act III with the Ironclad',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Ironclad', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_emerald', official: true,   icon: '💚', tier: 'bronze', pts: 15, name: 'Emerald',
        desc: 'Beat Act III with the Silent',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Silent', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_sapphire', official: true,  icon: '💙', tier: 'bronze', pts: 15, name: 'Sapphire',
        desc: 'Beat Act III with the Defect',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Defect', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_amethyst', official: true,  icon: '💜', tier: 'bronze', pts: 15, name: 'Amethyst',
        desc: 'Beat Act III with the Watcher',
        check: { type: 'win_multifield_value_and_field_eq', fields: ['character','character2','character3','character4'], value: 'Watcher', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_all_chars', official: true, icon: '✨', tier: 'gold',   pts: 40, name: 'Full Roster',
        desc: 'Beat Act III with all 4 characters',
        check: { type: 'all_achievements', ids: ['sts_ruby','sts_emerald','sts_sapphire','sts_amethyst'] } },

      // ── Ascension milestones ──
      { id: 'sts_asc1',      icon: '🔥', tier: 'bronze', pts: 10, name: 'Ascension Unlocked',
        desc: 'Unlock Ascension mode (beat Act II boss solo / Act III with 2+ players)',
        check: { type: 'field_gte', field: 'ascension', value: 1 } },
      { id: 'sts_asc5',      icon: '🔥', tier: 'silver', pts: 20, name: 'Ascending',
        desc: 'Reach Ascension 5',
        check: { type: 'field_gte', field: 'ascension', value: 5 } },
      { id: 'sts_asc10',     icon: '🔥', tier: 'gold',   pts: 35, name: 'High Climber',
        desc: 'Complete Ascension Level 10',
        check: { type: 'win_field_gte', field: 'ascension', value: 10 } },
      { id: 'sts_asc13',     icon: '🔥', tier: 'gold',   pts: 60, name: 'Double Act 3 Boss',
        desc: 'Complete Ascension Level 13',
        check: { type: 'win_field_gte', field: 'ascension', value: 13 } },

      // ── Official achievements (from rulebook) ──
      { id: 'sts_jaxxed', official: true,    icon: '💪', tier: 'silver', pts: 20, name: 'Jaxxed',
        desc: 'Hit the Strength limit (8)',
        check: { type: 'win_with_toggle', field: 'hitStrength' } },
      { id: 'sts_catalyst', official: true,  icon: '☠️',  tier: 'silver', pts: 20, name: 'Catalyst',
        desc: 'Hit the Poison limit (30)',
        check: { type: 'win_with_toggle', field: 'hitPoison' } },
      { id: 'sts_ninja', official: true,     icon: '🗡️', tier: 'silver', pts: 25, name: 'Ninja',
        desc: 'Play 7 Shivs in one turn',
        check: { type: 'win_with_toggle', field: 'play7shivs' } },
      { id: 'sts_powerful', official: true,  icon: '⚡', tier: 'silver', pts: 20, name: 'Powerful',
        desc: 'Have 7 Powers in play at once',
        check: { type: 'win_with_toggle', field: 'have7powers' } },
      { id: 'sts_barricaded', official: true,icon: '🛡️', tier: 'silver', pts: 20, name: 'Barricaded',
        desc: 'Hit the Block limit (20)',
        check: { type: 'win_with_toggle', field: 'hitBlock' } },
      { id: 'sts_nothing', official: true,   icon: '⚡', tier: 'gold',   pts: 40, name: 'You Are Nothing',
        desc: 'Defeat a Boss on turn 1',
        check: { type: 'win_with_toggle', field: 'bossT1' } },
      { id: 'sts_perfect', official: true,   icon: '❤️',  tier: 'gold',   pts: 35, name: 'Perfect',
        desc: 'Beat a Boss with all players at full HP',
        check: { type: 'win_with_toggle', field: 'hpFull' } },
      { id: 'sts_minimalist', official: true,icon: '🃏', tier: 'gold',   pts: 50, name: 'Minimalist',
        desc: 'Beat Act III with a 5 card deck or smaller',
        check: { type: 'win_field_lte_and_field_eq', field: 'deckSize', value: 5, condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_transient', official: true, icon: '👻', tier: 'gold',   pts: 40, name: 'The Transient',
        desc: 'Kill The Transient before it kills itself',
        check: { type: 'win_with_toggle', field: 'killedTransient' } },
      { id: 'sts_common', official: true,    icon: '📦', tier: 'gold',   pts: 40, name: 'Common Sense',
        desc: 'Beat Act III with no uncommons or rares',
        check: { type: 'win_with_toggle_and_field_eq', field: 'noRares', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_collector', official: true, icon: '🎒', tier: 'gold',   pts: 35, name: 'Collector',
        desc: 'Beat Act III with 12+ relics and Boss relics per player',
        check: { type: 'win_field_gte_and_field_eq', field: 'relicCount', value: 12, condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_lucky', official: true,     icon: '🎲', tier: 'silver', pts: 20, name: 'My Lucky Day',
        desc: 'Beat Act III with a Daily Climb',
        check: { type: 'win_with_toggle_and_field_eq', field: 'dailyClimb', condField: 'actsCleared', condValue: 'Act 3' } },
      { id: 'sts_infinity', official: true,  icon: '♾️', tier: 'gold',   pts: 50, name: 'Infinity',
        desc: 'Create an infinite card combo',
        check: { type: 'win_with_toggle', field: 'infiniteCombo' } },
      { id: 'sts_norelics', official: true,  icon: '🚫', tier: 'gold',   pts: 45, name: 'Who Needs Relics?',
        desc: 'Beat Act III with no relics or Boss relics',
        check: { type: 'win_with_toggle_and_field_eq', field: 'noRelics', condField: 'actsCleared', condValue: 'Act 3' } },

      // ── Play milestones ──
      { id: 'sts_10plays',   icon: '🎮', tier: 'silver', pts: 20, name: 'Veteran Climber',
        desc: 'Play 10 runs total',
        check: { type: 'min_plays', count: 10 } },
      { id: 'sts_10wins',    icon: '🏆', tier: 'gold',   pts: 35, name: 'Spire Slayer',
        desc: 'Win 10 runs',
        check: { type: 'min_wins', count: 10 } },

      // ── Platinum ──
      { id: 'sts_plat',      icon: '💎', tier: 'plat',   pts: 100, name: 'Spire Conquered',
        desc: 'Unlock all other Slay the Spire achievements',
        check: { type: 'all_achievements', ids: [
          'sts_ruby','sts_emerald','sts_sapphire','sts_amethyst','sts_all_chars',
          'sts_asc1','sts_asc5','sts_asc10','sts_asc13',
          'sts_jaxxed','sts_catalyst','sts_ninja','sts_powerful','sts_barricaded',
          'sts_nothing','sts_perfect','sts_minimalist','sts_transient',
          'sts_common','sts_collector','sts_lucky','sts_infinity','sts_norelics',
          'sts_10plays','sts_10wins',
        ]}},
    ]
  }
);
